import type { HudBoardConfig } from '@fnx/sl-engine';

/**
 * Opt-in Cleopatra HUD board visual proof config.
 *
 * Not imported by default hudConfig.ts. Enabled only when
 * `?slTest=1&slBoardVisualProof=1` patches runtime shell at bootstrap.
 */
export const cleopatraBoardVisualProofConfig = {
  enabled: true,
  elements: {
    brandTitle: {
      type: 'text',
      layer: 'hud',
      anchorTo: 'safeArea',
      anchor: 'top-center',
      offset: { y: 20 },
      textKey: 'hud.board.visualProof.title',
      styleRole: 'zoneTitle',
      zIndex: 10,
    },
    buyButton: {
      type: 'button',
      layer: 'hud',
      anchorTo: 'element',
      target: 'brandTitle',
      anchor: 'bottom-center',
      offset: { y: 48 },
      action: 'panel.paytable.open',
      enabledWhen: 'panel.paytable.canOpen',
      width: 132,
      height: 42,
      label: { type: 'text', textKey: 'hud.board.buyButton', styleRole: 'buttonLabel' },
      zIndex: 20,
    },
    balanceLabel: {
      type: 'text',
      layer: 'hud',
      anchorTo: 'zone',
      target: 'bottomHudBar',
      anchor: 'center-left',
      offset: { x: 200, y: -6 },
      textKey: 'hud.board.balanceLabel',
      styleRole: 'label',
      zIndex: 15,
    },
    balanceText: {
      type: 'text',
      layer: 'hud',
      anchorTo: 'element',
      target: 'balanceLabel',
      anchor: 'center-left',
      offset: { x: 82 },
      textFrom: 'balance.formatted',
      styleRole: 'statusPrimary',
      zIndex: 16,
    },
    winText: {
      type: 'text',
      layer: 'hud',
      anchorTo: 'element',
      target: 'balanceText',
      anchor: 'center-right',
      offset: { x: 16, y: 0 },
      textFrom: 'win.formatted',
      visibleWhen: 'win.visible',
      styleRole: 'statusPrimary',
      zIndex: 16,
    },
    buttonRow: {
      type: 'container',
      layer: 'hud',
      anchorTo: 'safeArea',
      anchor: 'top-right',
      offset: { x: -18, y: 18 },
      width: 216,
      height: 42,
      zIndex: 18,
    },
    settingsButton: {
      type: 'button',
      layer: 'hud',
      anchorTo: 'element',
      target: 'buttonRow',
      anchor: 'center-left',
      action: 'panel.settings.open',
      enabledWhen: 'panel.settings.canOpen',
      width: 66,
      height: 38,
      label: { type: 'text', textKey: 'hud.board.settingsPanel', styleRole: 'buttonLabel' },
      zIndex: 21,
    },
    soundButton: {
      type: 'button',
      layer: 'hud',
      anchorTo: 'element',
      target: 'settingsButton',
      anchor: 'center-right',
      offset: { x: 74 },
      action: 'panel.sound.open',
      enabledWhen: 'panel.sound.canOpen',
      width: 66,
      height: 38,
      label: { type: 'text', textKey: 'hud.board.soundPanel', styleRole: 'buttonLabel' },
      zIndex: 22,
    },
    paytableButton: {
      type: 'button',
      layer: 'hud',
      anchorTo: 'element',
      target: 'soundButton',
      anchor: 'center-right',
      offset: { x: 74 },
      action: 'panel.paytable.open',
      enabledWhen: 'panel.paytable.canOpen',
      width: 66,
      height: 38,
      label: { type: 'text', textKey: 'hud.board.paytablePanel', styleRole: 'buttonLabel' },
      zIndex: 23,
    },
  },
  portrait: {
    elements: {
      brandTitle: { anchor: 'top-center', offset: { y: 28 } },
      buyButton: { offset: { y: 46 } },
      buttonRow: { anchor: 'top-center', offset: { x: 0, y: 22 } },
      balanceLabel: { anchor: 'center', offset: { x: -80, y: -12 } },
      winText: { anchor: 'center-right', offset: { x: 12, y: 0 } },
    },
  },
  landscape: {
    elements: {
      brandTitle: { anchor: 'top-center', offset: { y: 20 } },
      buyButton: { offset: { y: 48 } },
      buttonRow: { anchor: 'top-right', offset: { x: -18, y: 18 } },
      balanceLabel: { anchor: 'center-left', offset: { x: 200, y: -6 } },
      winText: { anchor: 'center-right', offset: { x: 16, y: 0 } },
    },
  },
} satisfies HudBoardConfig;
